// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC01dIn-zItS-b-LJ2Ybsv3jzJuBYfkt3k',
    appId: '1:642755817217:web:3eb7c35e6773fd48adb500',
    messagingSenderId: '642755817217',
    projectId: 'petguardian-69cba',
    authDomain: 'petguardian-69cba.firebaseapp.com',
    storageBucket: 'petguardian-69cba.firebasestorage.app',
    measurementId: 'G-ZFFZWHW3GH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCUg4TVwMAAfazuTXMam-u6vlU9fOkNmAI',
    appId: '1:642755817217:android:a49739fa9d09d1efadb500',
    messagingSenderId: '642755817217',
    projectId: 'petguardian-69cba',
    storageBucket: 'petguardian-69cba.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAgLdmgRv1IKIVj46uG-9L_eGNyR_lZxXw',
    appId: '1:642755817217:ios:800f96f013071b71adb500',
    messagingSenderId: '642755817217',
    projectId: 'petguardian-69cba',
    storageBucket: 'petguardian-69cba.firebasestorage.app',
    iosBundleId: 'com.example.releaseReadyFlutterApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAgLdmgRv1IKIVj46uG-9L_eGNyR_lZxXw',
    appId: '1:642755817217:ios:800f96f013071b71adb500',
    messagingSenderId: '642755817217',
    projectId: 'petguardian-69cba',
    storageBucket: 'petguardian-69cba.firebasestorage.app',
    iosBundleId: 'com.example.releaseReadyFlutterApp',
  );
}
